# Generated by Django 5.0.9 on 2024-11-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('asignatura', models.CharField(max_length=255)),
                # Cambiar 'fecha_hora_salida' a dos campos separados
                ('fecha_salida', models.DateField(default=models.functions.Now())),
                ('hora_salida', models.TimeField(default=models.functions.Now())),
                # Cambiar 'fecha_hora_devolucion' a dos campos separados
                ('fecha_devolucion', models.DateField(default=models.functions.Now())),
                ('hora_devolucion', models.TimeField(default=models.functions.Now())),
                ('cod_articulo', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
