# Generated by Django 5.0.9 on 2024-11-10 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='fecha_devolucion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='hora_devolucion',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='hora_salida',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
