# Generated by Django 5.0.9 on 2024-11-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0004_alter_solicitudarticulo_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarticulo',
            name='tipo_solicitante',
            field=models.CharField(choices=[('docente', 'Docente'), ('otro', 'Otro')], default='otro', max_length=10),
        ),
    ]
