# Generated by Django 5.0.9 on 2024-11-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0005_solicitudarticulo_tipo_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarticulo',
            name='estado_devolucion',
            field=models.CharField(choices=[('devuelto', 'Devuelto'), ('no devuelto', 'No devuelto')], default='no devuelto', max_length=20),
        ),
    ]
