# Generated by Django 5.0.9 on 2024-11-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0013_solicitudarticulo_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudarticulo',
            name='articulo',
        ),
    ]
