# Generated by Django 5.0.9 on 2024-11-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0015_solicitudarticulo_nombre_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudarticulo',
            name='nombre_articulo',
        ),
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='cod_articulo',
            field=models.CharField(max_length=50),
        ),
    ]
