# Generated by Django 5.0.9 on 2024-11-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0021_alter_solicitudarticulo_estado_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarticulo',
            name='encargado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
