# Generated by Django 5.0.9 on 2024-11-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0022_solicitudarticulo_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='encargado',
            field=models.CharField(max_length=255),
        ),
    ]
