# Generated by Django 5.0.9 on 2024-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0023_alter_solicitudarticulo_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='encargado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
