# Generated by Django 5.0.9 on 2024-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_articulos', '0024_alter_solicitudarticulo_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarticulo',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudarticulo',
            name='encargado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
