# Generated by Django 5.0.9 on 2024-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('cod_articulo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código Artículo')),
                ('grupo', models.CharField(max_length=4, verbose_name='Grupo')),
                ('tipo_articulo', models.CharField(max_length=6, verbose_name='Tipo de Artículo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('observacion', models.TextField(verbose_name='Observación')),
            ],
        ),
    ]
