# Generated by Django 5.0.9 on 2024-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0002_alter_articulo_cod_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='grupo',
            field=models.CharField(choices=[('CFTN', 'CFTN'), ('IPN', 'IPN')], max_length=4),
        ),
    ]
