# Generated by Django 5.0.9 on 2024-11-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0003_alter_articulo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cod_articulo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código Artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='grupo',
            field=models.CharField(max_length=4, verbose_name='Grupo'),
        ),
    ]
