# Generated by Django 5.0.9 on 2024-11-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0004_alter_articulo_cod_articulo_alter_articulo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cod_articulo',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código Artículo'),
        ),
    ]
