# Generated by Django 5.0.9 on 2024-11-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0005_alter_articulo_cod_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='dado_de_baja',
            field=models.BooleanField(default=False),
        ),
    ]
