# Generated by Django 5.0.9 on 2024-11-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0006_alter_articulo_cod_articulo'),
        ('gestor_inventario', '0006_articulo_dado_de_baja'),
    ]

    operations = [
    ]
