# Generated by Django 5.0.9 on 2024-11-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0007_merge_20241115_1958'),
        ('gestor_inventario', '0007_merge_20241115_2105'),
    ]

    operations = [
    ]
