# Generated by Django 5.0.9 on 2024-11-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0008_merge_20241120_1403'),
        ('gestor_inventario', '0008_merge_20241120_1410'),
    ]

    operations = [
    ]
