# Generated by Django 5.0.9 on 2024-11-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0009_merge_20241120_2352'),
        ('gestor_inventario', '0009_merge_20241121_0000'),
    ]

    operations = [
    ]
