# Generated by Django 5.0.9 on 2024-11-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0010_merge_20241122_1659'),
        ('gestor_inventario', '0010_merge_20241123_0043'),
    ]

    operations = [
    ]
