# Generated by Django 5.0.9 on 2024-11-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_inventario', '0010_merge_20241121_2013'),
        ('gestor_inventario', '0011_merge_20241126_1923'),
    ]

    operations = [
    ]
